version: '3.8'

services:
  frontend:
    build:
      context: ./client/myforum
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/viteforum
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
